language: c
sudo: required
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo service postgresql stop; fi
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
matrix:
  include:
    - os: osx
      env: OCAML_VERSION=4.07 PINS="ocsigenserver:https://github.com/ocsigen/ocsigenserver.git eliom:https://github.com/ocsigen/eliom.git ocsigen-toolkit:https://github.com/ocsigen/ocsigen-toolkit.git" PACKAGE=ocsigen-start
    - os: linux
      env: OCAML_VERSION=4.03 PINS="eliom:https://github.com/ocsigen/eliom.git ocsigen-toolkit:https://github.com/ocsigen/ocsigen-toolkit.git" PACKAGE=ocsigen-start
    - os: linux
      env: OCAML_VERSION=4.05 PINS="eliom:https://github.com/ocsigen/eliom.git ocsigen-toolkit:https://github.com/ocsigen/ocsigen-toolkit.git" PACKAGE=ocsigen-start
    - os: linux
      env: OCAML_VERSION=4.06 PINS="eliom:https://github.com/ocsigen/eliom.git ocsigen-toolkit:https://github.com/ocsigen/ocsigen-toolkit.git" PACKAGE=ocsigen-start
    - os: linux
      env: OCAML_VERSION=4.07 PINS="ocsigenserver:https://github.com/ocsigen/ocsigenserver.git eliom:https://github.com/ocsigen/eliom.git ocsigen-toolkit:https://github.com/ocsigen/ocsigen-toolkit.git" PACKAGE=ocsigen-start
branches:
  only:
  - master